import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import LogoutBtn from "./logoutBtn";
import "./login.css"
import { Navbar, Nav } from "react-bootstrap";
import React from "react";
import 'bootstrap/dist/css/bootstrap.min.css'
import NavTab from "./navTab";
import Avatar from "./user";
import UserCheck from "./userCheck";
import { Black_Han_Sans } from "next/font/google";
import { Jua } from "next/font/google";
import { Container,Divider } from "@mui/material";
import FavoriteIcon from '@mui/icons-material/Favorite';


const black_Han_Sans = Black_Han_Sans({ weight: ['400'], subsets: ["latin"] });
const jua = Jua({ weight: ['400'], subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)

  return (
    <html>
      <body>

        <div className={`navbar ${black_Han_Sans.className}`}  >



          <Link href="/" className="logo">
            <div className="logo-container" style={{width:'90px',marginLeft:'2rem',display:'flex'}}>
              <img src="/logo.svg" className="titleLogo" />
              <img src="/sportsconnect.svg" className="logoName" style={{marginLeft:'-1rem'}}/>
            </div>
          </Link>



          <Link href="/">Home</Link>



          <Link href="/market">Market</Link>


          <Link href="/write">Write</Link>




          {
            session ? <div style={{marginRight:'2rem'}}>

              <a href="/likeList"><FavoriteIcon/></a>         

              <a href={"/user/" + session.user.email}>
              <Avatar/></a><span style={{marginRight:'1rem'}}>{session.user.email}</span> <LogoutBtn /> </div> : 
            <LoginBtn />
          }


        </div>
        {/* <Divider component="div" style={{ borderColor: 'gray' }}  ></Divider> */}

        {/* <NavTab><div></div></NavTab> */}

        <div className={jua.className}>
          {children}
        </div>




      </body>
    </html>
  );
}
